version:  '3.7'

services:
    postgres:
        image: postgres
        restart: on-failure
        ports:
            - '5433:5432'
    php:
        build:
          context: .
          dockerfile: docker/php-fpm/Dockerfile
        restart: on-failure
        ports:
            - '9002:9000'
        volumes:
            - ./:/usr/src/app:cached
        env_file:
          - .env
        user: 1000:1000 
        links:
            - postgres
    nginx:
        image: nginx:1.17.5-alpine
        restart: on-failure
        depends_on:
          - php
        volumes:
          - './:/usr/src/app'
          - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
          - './logs/nginx/:/var/log/nginx:cached'
        ports:
          - '8080:80'
    
       


    